### ISSUE TITLE
java.lang.IllegalArgumentException: jitter should be between 0.0 and 1.0

### ISSUE THREAD

**Issue by halysongoncalves** [dyte-io/socketio-kotlin#2]
When trying to create a connection, I receive the error:

java.lang.IllegalArgumentException: jitter should be between 0.0 and 1.0
                                                                                                    	at io.dyte.socketio.Backoff.<init>(Manager.kt:353)
                                                                                                    	at io.dyte.socketio.Backoff.<init>(Manager.kt:343)
                                                                                                    	at io.dyte.socketio.Manager.<init>(Manager.kt:41)
                                                                                                    	at io.dyte.socketio.IO.lookup(io.kt:26)
                                                                                                    	at io.dyte.socketio.IO.socket(io.kt:10)
                                                                                                    	at com.arena.network.socket.socketio.SocketIO.<init>(SocketIO.kt:9)

    val socket = IO.socket(url, IOOptions())

![Captura de Tela 2024-03-12 às 10 48 14](https://github.com/dyte-io/socketio-kotlin/assets/5872045/0ce8a36c-a004-470b-aab0-85006bd7e5f8)
![Captura de Tela 2024-03-12 às 10 48 10](https://github.com/dyte-io/socketio-kotlin/assets/5872045/40160af7-544b-403a-877b-cace327a3966)
![Captura de Tela 2024-03-12 às 10 47 57](https://github.com/dyte-io/socketio-kotlin/assets/5872045/9804fdcc-a1a4-4781-ad04-ad7e115f670d)

**Comment by halysongoncalves** [comment]
@harshs-dyte @palashgo @swapnilmadavi

**Comment by halysongoncalves** [comment]
news?

**Comment by palashgo** [comment]
@halysongoncalves Missed this, checking

**Comment by halysongoncalves** [comment]
Were you able to investigate the problem? @palashgo

**Comment by palashgo** [comment]
@halysongoncalves It should work now with the `1.0.7`, the tests were also failing earlier

I will setup some github action checks to run tests on PRs
